### ISSUE TITLE
assertContains - not empty string

### ISSUE THREAD

**Issue by SpacePossum** [PHPUnitGoodPractices/PHPUnitGoodPractices#14]
```php
$this->assertContains('', 'a');
```

fun fact is that PHPUnit fails with
```
There was 1 error:

1) myTest::testA
mb_strpos(): Empty delimiter

/home/possum/work/phpunit/src/Framework/Constraint/StringContains.php:59
```

technically any string contains `''`, but it is a useless check. WDYT, raise a warning for it?

**Comment by SpacePossum** [comment]
any thoughts @keradus ? I could try to make something or close this

**Comment by keradus** [comment]
I would say it's very edge case, so it's not on my prio list, yet if there would be a PR, I would accept it ;)

**Comment by SpacePossum** [comment]
I'll come back to this when I've that PR ;)
