### ISSUE TITLE
assertEquals(true|false, $actual)

### ISSUE THREAD

**Issue by alister** [PHPUnitGoodPractices/PHPUnitGoodPractices#27]
Suggest Use the more specific `->assertTrue()` or `->assertFalse()` instead of `->assertEquals(bool, ...)`.

**Comment by keradus** [comment]
Hi @alister !
This is out of scope of this package.
This package is executed on runtime. And on runtime, when `->assertEquals` is called, we do not know if passed boolean was passed using expression or concrete true | false native constant.

But don't worry, we could analyse that via Static Code Analysis and you know what? An automated code fixer for this case and many more is already offered via
https://packagist.org/packages/friendsofphp/php-cs-fixer !
