### ISSUE TITLE
Allow `assertStringEqualsFile`

### ISSUE THREAD

**Issue by SpacePossum** [PHPUnitGoodPractices/PHPUnitGoodPractices#30]
Currently `IdentityOverEqualityTrait` reports when using `assertStringEqualsFile` , however there is not a more strict one.
The only issue with the original method is that, since `strict types` is not declared, the arguments passed might not be a string and get auto cast. Besides that the weaker `equals` of two strings is as good as the `same` counter part.

**Comment by keradus** [comment]
> Besides that the weaker equals of two strings is as good as the same counter part.

as long as you know that both `expected` and `actual` are strings, right? but if you don't, using `equals` might cause you troubles with types autocasting.

**Comment by keradus** [comment]
@SpacePossum , see #31

**Comment by SpacePossum** [comment]
~nevermind~ ;)
thanks!
