### ISSUE TITLE
Add support for PHPUnit 10

### ISSUE THREAD

**Issue by Wirone** [PHPUnitGoodPractices/PHPUnitGoodPractices#63]
Currently `composer.json`'s constraint for `phpunit/phpunit` does not allow installation with PHPUnit 10.

- [Changelog for 10.0](https://github.com/sebastianbergmann/phpunit/blob/10.0.0/ChangeLog-10.0.md)
- [Changelog for 10.1](https://github.com/sebastianbergmann/phpunit/blob/10.1.0/ChangeLog-10.1.md)

Please add support for latest PHPUnit version.

---

FYI: it looks like [it's not possible](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/6884#issuecomment-1675400947).

**Comment by keradus** [comment]
here you go, @Wirone : https://github.com/PHPUnitGoodPractices/Traits/compare

**Comment by zengboin** [comment]
When will support for PHPUnit 10 be updated?

**Comment by Wirone** [comment]
@zengboin [it won't be](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/6884#issuecomment-1675400947). Trait approach with wrapped PHPUnit's methods is impossible with PHPUnit v10.
