### ISSUE TITLE
AssertCount - strict test

### ISSUE THREAD

**Issue by SpacePossum** [PHPUnitGoodPractices/PHPUnitGoodPractices#9]
Only allow AssertCount with expected `int > 0`, current PHPUnit checks `int` only.
In theory a `Countable` can return a negative number, however this should never be considered valid (i.e. abuse of the interface)

**Comment by keradus** [comment]
:+1:
but imo
```diff
-int > 0
+int >= 0
```

**Comment by keradus** [comment]
Adressed in #10

**Comment by SpacePossum** [comment]
Ah yes typo, good catch.
Beside testing the given `expected` value you can also test the `count` returned by a `\Countable` object for being `>=0`. Than as a second issue, you could even go as far as testing the `assertGreaterThan` for `not -INF` (and the counter part `LessThan`). But these are all a bit of edge cases.

**Comment by SpacePossum** [comment]
closing as #10 is on its way :)  :+1:

**Comment by keradus** [comment]
passed countable object is not part of phpunit, imo outside of scope of this project
checking `! -INF` is really edgeeee case ;)
